# Use an official Node.js runtime as a parent image
FROM node:latest

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application files from the parent directory
COPY . .

# Expose the port
EXPOSE ${PORT}

# Start your application
CMD ["node", "app.js"]
